### ISSUE TITLE
Usage Instruction

### ISSUE THREAD

**Issue by Philip-Nunoo** [tprzytula/Meteor-Remember-Me#25]
I came across this wonderful package but had issues using it following the README

Instead, I got it working by doing this

```js
import { factory as RememberMe } from 'meteor/tprzytula:remember-me';

rememberMeObj.loginWithPassword(email, password, (err) => {
        if (err) {
          console.error(err);
        } else {
        }
    });
  }, rememberMe);
```
If this is the case, it would be best to update the readme as such.

Leaving this here should in case someone faces similar issue using this package.

**Comment by tprzytula** [comment]
Hi @Philip-Nunoo,

Thank you for reporting the problems! I'm glad that you found a short term workaround.

I'm afraid that it might be something strange in your babel configuration, any ideas?

In my free time I will try to reproduce this issue and if that happens I will release the fix for it. In the meantime could you tell me what exactly the error was and which version of Meteor did you use? Cheers!

**Comment by evg1n** [comment]
> I came across this wonderful package but had issues using it following the README
> 
> Instead, I got it working by doing this
> 
> ```js
> import { factory as RememberMe } from 'meteor/tprzytula:remember-me';
> 
> rememberMeObj.loginWithPassword(email, password, (err) => {
>         if (err) {
>           console.error(err);
>         } else {
>         }
>     });
>   }, rememberMe);
> ```
> 
> If this is the case, it would be best to update the readme as such.
> 
> Leaving this here should in case someone faces similar issue using this package.

I don't understand your example, can you clarify?

What is rememberMeObj?

**Comment by tprzytula** [comment]
This does not seem like an issue within this library.
Closing for now, feel free to open if you will come with any updates on it.
